### ISSUE TITLE
网站名字修改建议

### ISSUE THREAD

**Issue by wangzhankun** [leiroc/insults#1]
我个人认为网站起名`辱华事件回忆录`本身起回忆录不太合适。在中文语境下，回忆一词一般是中性偏好的，对美好事情的回忆之类的。另外，回忆一词也更偏向于是个人的经历回忆。因此我建议修改为`耻辱名录`之类的词语可能更合适一些。但是目前我还没有想到比较好的表达。

**Comment by leiroc** [comment]
确实这个问题我自己也一直很纠结，我也想换一个名字，但是也还没想好换成什么，你也帮着一起想想吧，回忆录确实一般都指向好的一方面！ @wangzhankun 
暂时改成了：辱华事件备忘录

**Comment by leiroc** [comment]
列几个可选的：
1. 辱华事件黑名单
2. 辱华黑名单
3. 辱华事件备忘录
4. 辱华备忘录

看看那个合适点？

**Comment by wangzhankun** [comment]
网站名“辱华事件备忘录”应该比较合适。我刚刚翻到一个谷歌浏览器提示不安全的网站  https://www.iw77.com/archives/  ，里面的部分内容与  https://insults.cn/  接近，不清楚前者这个网站是不是钓鱼网站？

**Comment by leiroc** [comment]
看起来是的，这个网站好像是一个采集站，一直在采集我的；
