### ISSUE TITLE
瑞典电视台瑞典新闻栏目辱华事件

### ISSUE THREAD

**Issue by wangzhankun** [leiroc/insults#2]
[瑞典辱华事件](https://baike.baidu.com/item/%E7%91%9E%E5%85%B8%E8%BE%B1%E5%8D%8E%E4%BA%8B%E4%BB%B6/22888340)

**Comment by leiroc** [comment]
@wangzhankun 谢谢添加，已收藏记录：[瑞典辱华事件：瑞典电视台如此“幽默”辱华，我们不接受！瑞典，你必须给中国人民道歉！](https://insults.cn/posts/42762/)
