### ISSUE TITLE
Notepad++作者在推特上辱华

### ISSUE THREAD

**Issue by JeffongTan** [leiroc/insults#3]
![image](https://user-images.githubusercontent.com/49052669/116668713-46bcc480-a9d0-11eb-893c-c58428065d44.png)
![image](https://user-images.githubusercontent.com/49052669/116668725-4ae8e200-a9d0-11eb-99e3-f32f8bf54a34.png)
![image](https://user-images.githubusercontent.com/49052669/116668750-54724a00-a9d0-11eb-9856-9ad51a9abfec.png)

**Comment by leiroc** [comment]
@JeffongTan 已添加：https://insults.cn/posts/65025/ 多谢提交。
