### ISSUE TITLE
三西猴（Ciro Santilli）在 Github 各种 RH

### ISSUE THREAD

**Issue by shenlebantongying** [leiroc/insults#4]
这是他的个人主页 https://github.com/cirosantilli
你从网上搜也能搜到很多他的 RH 记录

他收集，储存， 散播各种虚假伪造的资料。

比如说这个仓库 https://github.com/cirosantilli/china-dictatorship

**Comment by leiroc** [comment]
@shenlebantongying 感谢提交，这个人有点疯狂了。我就不给加到记录里面了，因为加进去，看到的人就会更加多。对于这些信息不是所有人都有分别真伪的能力。害怕有些人信了他的，或者被他诱导。所以还是让他消声少曝光的好，这些人国家肯定一直在监控的，我们可以放心。

**Comment by leiroc** [comment]
欢迎提交完整的记录哈，谢谢您
