### ISSUE TITLE
编程随想 RH

### ISSUE THREAD

**Issue by shenlebantongying** [leiroc/insults#5]
https://program-think.blogspot.com/

例子：

抹黑新疆棉花 https://program-think.blogspot.com/2021/03/weekly-share-151.html
贬低国人的奋斗精神 https://program-think.blogspot.com/2021/01/weekly-share-149.html
各种唱衰华为 https://program-think.blogspot.com/2020/09/weekly-share-148.html

**Comment by leiroc** [comment]
这个人我也关注到过，是真的懒得去看他。网站已经被国内封了，说明国家已经重视，而且已经关注他了。我们就没必要再去给他曝光，增加“人气了”。而且大部分人民也看不到他的这些言论的。 @shenlebantongying

**Comment by shenlebantongying** [comment]
要不你把我的两条 issues 删掉吧，停在主页挺烦的

![image](https://user-images.githubusercontent.com/20123683/122600301-910c0a80-d03d-11eb-939a-8db284119cd6.png)
