### ISSUE TITLE
本人已知的github辱华政治repos

### ISSUE THREAD

**Issue by Sherlockcxk** [leiroc/insults#6]
https://github.com/cirosantilli/china-dictatorship
https://github.com/webdao/tuidang/

**Comment by leiroc** [comment]
感谢关注，你发的这2个我之前关注过，也有其他人提过的。但是我不知道该怎么写，要写成这样：https://insults.cn/posts/41587/
类似，我希望你可以像这样提pr，还有就是他们的行为越少人知道越好，免得误导其他人，毕竟每个人最后看了观点可能不一样。
